from __future__ import annotations

from textwrap import dedent

from ai_bot.analyzer.result import AnalysisResult


def _meta_footer(run_id: str, result: AnalysisResult) -> str:
    return (
        f"\n\n---\n"
        f"🤖 ai-bot (model={result.model}, confidence={result.confidence:.2f}, "
        f"category={result.category})\n"
        f"Run: `{run_id}` | Cost: ${result.cost_usd:.3f} | Tool calls: {result.tool_calls_count}\n"
    )


def build_code_bug_issue_body(
    *, result: AnalysisResult, service: str, commit_sha: str, run_id: str,
) -> str:
    return dedent(f"""\
        ## 🐛 코드 버그 — 자동 PR 생성됨

        **서비스**: {service} @ `{commit_sha[:8]}`
        **카테고리**: CODE_BUG (confidence: {result.confidence:.2f})

        ### 추정 원인
        {result.root_cause}

        AI 봇이 자동으로 패치 PR을 생성했습니다. 본 Issue와 연결됩니다.
        """) + _meta_footer(run_id, result)


def build_code_bug_pr_body(
    *, result: AnalysisResult, issue_number: int, run_id: str,
) -> str:
    return dedent(f"""\
        ## 🤖 AI 자동 생성 PR

        > ⚠️ This PR was generated by AI. Review carefully before merging.

        Fixes #{issue_number}

        ### 추정 원인
        {result.root_cause}

        ### 머지 전 확인 사항
        - [ ] 패치가 실제 root cause를 해결하는지 (증상 완화만이 아닌지)
        - [ ] 기존 테스트가 깨지지 않는지 (CI 통과 확인)
        - [ ] 패치 범위가 적절한지 (다른 곳에도 같은 버그가 있는지)
        """) + _meta_footer(run_id, result)


def build_data_anomaly_issue_body(
    *, result: AnalysisResult, service: str, commit_sha: str, run_id: str,
) -> str:
    sql_block = "\n\n".join(f"```sql\n{q}\n```" for q in result.verification_sql) or "(none)"
    logql_block = "\n\n".join(f"```logql\n{q}\n```" for q in result.verification_logql) or "(none)"

    return dedent(f"""\
        ## 🔎 데이터 이상 추정 — 코드 수정 불필요

        **서비스**: {service} @ `{commit_sha[:8]}`
        **카테고리**: DATA_ANOMALY (confidence: {result.confidence:.2f})

        ### 가설
        {result.data_hypothesis}

        ### 추정 원인
        {result.root_cause}

        ### ✅ 검증 SQL (운영 read-replica 권장)

        {sql_block}

        ### ✅ 검증 LogQL

        {logql_block}

        ### ⚠️ 이 Issue는 코드 PR을 자동 생성하지 않았습니다
        AI 분석 결과 코드 로직 자체에는 명백한 결함이 보이지 않습니다.
        잘못된 코드 패치는 진짜 원인(데이터 정합성)을 가릴 수 있어
        사람의 판단을 요청드립니다.
        """) + _meta_footer(run_id, result)


def build_infra_issue_body(
    *, result: AnalysisResult, service: str, commit_sha: str, run_id: str,
) -> str:
    checklist = "\n".join(f"- [ ] {item}" for item in result.infra_checklist) or "- [ ] (none provided)"
    metrics = "\n\n".join(f"```logql\n{m}\n```" for m in result.related_metrics) or "(none)"

    return dedent(f"""\
        ## ⚙️ 인프라 이슈 추정 — 코드 수정 불필요

        **서비스**: {service} @ `{commit_sha[:8]}`
        **카테고리**: INFRA_ISSUE (confidence: {result.confidence:.2f})

        ### 추정 원인
        {result.root_cause}

        ### ✅ 점검 체크리스트
        {checklist}

        ### 관련 메트릭/쿼리

        {metrics}
        """) + _meta_footer(run_id, result)


def build_benign_pr_body(
    *, result: AnalysisResult, issue_number: int, run_id: str,
) -> str:
    return dedent(f"""\
        ## 🔇 노이즈 에러 처리

        > ⚠️ This PR was generated by AI. Review carefully before merging.

        Fixes #{issue_number}

        **카테고리**: BENIGN_ERROR (confidence: {result.confidence:.2f})

        ### 무엇을 바꿨나
        에러가 외부의 정상적 조건(클라이언트 disconnect 등)에 대한 반응이라
        ExceptionHandler를 추가해 ERROR 대신 INFO 레벨로 로깅합니다.

        ### 추정 원인
        {result.root_cause}

        ### 머지 전 확인 사항
        - [ ] 이 예외가 정말 클라이언트/외부 원인인지 (서버가 느려서가 아닌지)
        - [ ] 다른 endpoint에서도 같은 패턴이 있는지
        - [ ] 연결된 Issue의 alert rule 조정 제안 검토
        """) + _meta_footer(run_id, result)


def build_benign_alert_proposal_body(
    *, result: AnalysisResult, related_pr_number: int, run_id: str,
) -> str:
    proposal = result.alert_rule_proposal or "(no specific proposal)"
    return dedent(f"""\
        ## 🔇 노이즈 에러 추정 — 알림 규칙 조정 제안

        관련 PR #{related_pr_number}에서 ExceptionHandler를 추가했습니다.
        추가로 다음 알림 규칙 조정을 권장하지만, **AI는 alert rule을
        자동 수정하지 않습니다**. 사람이 검증 후 수동 적용해주세요.

        ### 조정 제안 (수동 적용)

        ```yaml
        # infra/grafana/provisioning/alerting/alerts.yaml
        - title: AI Bot - High Error Log Rate
          query: |
            sum by (commit_sha, service) (
              count_over_time({{job="spring-boot-demo"}} | json
                | level="ERROR"
                | {proposal}
                [5m])
            )
        ```

        ### ⚠️ 적용 전 체크리스트
        - [ ] 이 예외가 전체 ERROR의 다수를 차지하는지 (LogQL로 확인)
        - [ ] 정말 클라이언트 측 원인인지 (서버 측 성능 문제로 클라이언트가 포기한 게 아닌지)
        - [ ] 다른 운영자의 검토 (이 조정으로 진짜 인시던트를 놓칠 위험)
        """) + _meta_footer(run_id, result)


def build_insufficient_context_issue_body(
    *, result: AnalysisResult, service: str, commit_sha: str, run_id: str,
) -> str:
    return dedent(f"""\
        ## ⚠️ 분석 불가 — 추가 컨텍스트 필요

        **서비스**: {service} @ `{commit_sha[:8]}`
        **카테고리**: INSUFFICIENT_CONTEXT (confidence: {result.confidence:.2f})

        ### AI의 결론
        {result.root_cause}

        ### 권장 다음 단계
        AI가 사용 가능한 정보(스택 트레이스, 로그, 코드)만으로는 원인을 단정할 수
        없습니다. 다음 중 하나가 도움이 될 수 있습니다.

        - 인접 마이크로서비스의 같은 시간대 로그 확인
        - 분산 트레이싱 (Tempo/Jaeger) 확인
        - 인프라 메트릭 (DB, 네트워크) 시계열 확인
        """) + _meta_footer(run_id, result)


def build_slack_message(
    *,
    category: str,
    issue_url: str,
    pr_url: str | None,
    confidence: float,
    cost_usd: float,
    latency_ms: int,
    short_root_cause: str,
) -> str:
    latency_s = latency_ms / 1000
    meta = f"confidence: {confidence:.2f} | ${cost_usd:.3f} | {latency_s:.1f}s"

    if category == "CODE_BUG":
        return (
            f"✅ PR 생성됨 — {short_root_cause}\n"
            f"{meta}\n"
            f"Issue: {issue_url}\n"
            f"PR: {pr_url}"
        )
    if category == "BENIGN_ERROR":
        return (
            f"🔇 노이즈 에러 처리 PR 생성됨 — {short_root_cause}\n"
            f"{meta}\n"
            f"Issue: {issue_url}\n"
            f"PR: {pr_url}"
        )
    if category == "DATA_ANOMALY":
        return (
            f"🔎 데이터 조사 필요 — {short_root_cause}\n"
            f"PR은 생성하지 않았습니다. 검증 쿼리는 Issue 본문 참고.\n"
            f"{meta}\n"
            f"Issue: {issue_url}"
        )
    if category == "INFRA_ISSUE":
        return (
            f"⚙️ 인프라 점검 필요 — {short_root_cause}\n"
            f"{meta}\n"
            f"Issue: {issue_url}"
        )
    if category == "INSUFFICIENT_CONTEXT":
        return (
            f"⚠️ 분석 불가 (추가 컨텍스트 필요) — {short_root_cause}\n"
            f"{meta}\n"
            f"Issue: {issue_url}"
        )
    return f"❓ unknown category {category}: {short_root_cause}\nIssue: {issue_url}"
